namespace MailServer.Domain.Enums;

/// <summary>
/// Where a certificate came from, which determines how it is renewed and how far it can be
/// trusted.
/// </summary>
/// <remarks>
/// Persisted as an integer, so the values are fixed. Adding a source means adding a value;
/// renumbering means silently reinterpreting every existing row.
/// </remarks>
public enum CertificateSource
{
    /// <summary>
    /// Generated by this server. Not publicly trusted, and never substituted for a
    /// certificate from any other source — see <c>CertificateRenewalPolicy</c>.
    /// </summary>
    SelfSigned = 0,

    /// <summary>Issued by an ACME certificate authority such as Let's Encrypt (Milestone 4).</summary>
    Acme = 1,

    /// <summary>Imported from a PFX/PKCS#12 file supplied by the operator.</summary>
    ImportedPfx = 2,

    /// <summary>
    /// Held in the Windows certificate store at <c>LocalMachine\My</c> and referenced by
    /// thumbprint. The private key stays in the store; this server never exports it.
    /// </summary>
    WindowsStore = 3,
}
