using System.Globalization;
using System.Text;
using MailServer.Application.Abstractions.Platform;
using MailServer.Application.Abstractions.Smtp;

namespace MailServer.Infrastructure.Smtp.Outbound;

/// <summary>
/// Composes a delivery status notification as a single-part <c>text/plain</c> message.
/// </summary>
/// <remarks>
/// See <see cref="IDsnComposer"/>'s remarks for why this is plain text rather than RFC 3464's
/// full <c>multipart/report</c> structure: MIME support is not available until Milestone 9, and
/// a message honestly documented as a human-readable notice, legible in every mail client, beats
/// a machine-parsable structure this milestone cannot build correctly.
/// </remarks>
internal sealed class PlainTextDsnComposer(IServerIdentityProvider serverIdentity) : IDsnComposer
{
    public DsnMessage Compose(DsnRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);

        string subject = request.IsDelayWarning
            ? "Delivery Status Notification (Delay)"
            : "Delivery Status Notification (Failure)";

        string messageId = $"<{Guid.NewGuid():N}@{serverIdentity.Hostname}>";
        string date = request.NowUtc.UtcDateTime.ToString(
            "ddd, dd MMM yyyy HH:mm:ss", CultureInfo.InvariantCulture) + " +0000";

        StringBuilder message = new();

        message.Append("From: Mail Delivery System <MAILER-DAEMON@").Append(serverIdentity.Hostname).Append(">\r\n");
        message.Append("To: <").Append(request.OriginalReversePath.Value).Append(">\r\n");
        message.Append("Subject: ").Append(subject).Append("\r\n");
        message.Append("Date: ").Append(date).Append("\r\n");
        message.Append("Message-ID: ").Append(messageId).Append("\r\n");

        // RFC 3834: marks this as generated by software, not a person, so that a mail loop
        // between two auto-responders (or between this and another bounce) terminates instead
        // of alternating forever. This server also never re-bounces a message that already
        // carries one - see OutboundQueueItem.ShouldGenerateDsnOnFailure.
        message.Append("Auto-Submitted: auto-replied\r\n");
        message.Append("Content-Type: text/plain; charset=utf-8\r\n");
        message.Append("\r\n");

        message.Append("This is the mail system at host ").Append(serverIdentity.Hostname).Append(".\r\n\r\n");

        if (request.IsDelayWarning)
        {
            message.Append(
                "Your message has not yet been delivered. This is only a warning; the message " +
                "remains queued and delivery will keep being retried. No action is required.\r\n\r\n");
        }
        else
        {
            message.Append(
                "I'm sorry to inform you that your message could not be delivered to one or " +
                "more recipients. It has not been retried further.\r\n\r\n");
        }

        message.Append("For further assistance, please contact your system administrator.\r\n\r\n");

        message.Append("  <").Append(request.FailedRecipient.Value).Append(">: ");

        if (request.ReplyCode is { } code)
        {
            message.Append(code);

            if (request.EnhancedStatus is not null)
            {
                message.Append(' ').Append(request.EnhancedStatus);
            }

            message.Append(' ');
        }

        message.Append(request.Diagnostic ?? "no further detail is available");

        if (request.RemoteMta is not null)
        {
            message.Append(" (host ").Append(request.RemoteMta).Append(')');
        }

        message.Append("\r\n");

        TimeSpan queued = request.NowUtc - request.FirstQueuedUtc;
        message.Append("\r\nThis message has been in the queue for ")
            .Append(FormatDuration(queued))
            .Append(".\r\n");

        byte[] content = Encoding.UTF8.GetBytes(message.ToString());

        return new DsnMessage(content, request.OriginalReversePath, subject);
    }

    private static string FormatDuration(TimeSpan span)
    {
        if (span.TotalHours >= 1)
        {
            return $"{(int)span.TotalHours} hour(s)";
        }

        return $"{Math.Max(1, (int)span.TotalMinutes)} minute(s)";
    }
}
