using System.Diagnostics.CodeAnalysis;
using System.Text;
using MailServer.Domain.Exceptions;

namespace MailServer.Domain.ValueObjects;

/// <summary>
/// An RFC 5321 mailbox address: a local-part and a domain.
/// </summary>
/// <remarks>
/// <para>
/// <b>Local-part case sensitivity.</b> RFC 5321 §2.4 makes the local-part case-sensitive and
/// reserves its interpretation to the receiving host. In practice every significant mail
/// system treats it case-insensitively, and users expect <c>Sales@</c> and <c>sales@</c> to
/// reach the same mailbox. This product therefore:
/// </para>
/// <list type="bullet">
///   <item><description>preserves the original local-part in <see cref="LocalPart"/> for
///   display and for reproducing headers faithfully; and</description></item>
///   <item><description>matches and stores uniqueness on <see cref="NormalizedValue"/>,
///   which lower-cases the local-part.</description></item>
/// </list>
/// <para>
/// Quoted local-parts (<c>"odd name"@example.com</c>) are accepted because they are legal and
/// do occur, but they are never generated by this product.
/// </para>
/// </remarks>
public sealed class EmailAddress : IEquatable<EmailAddress>, IComparable<EmailAddress>
{
    /// <summary>Maximum local-part length in octets (RFC 5321 §4.5.3.1.1).</summary>
    public const int MaxLocalPartLength = 64;

    /// <summary>Maximum forward-path length in octets (RFC 5321 §4.5.3.1.3).</summary>
    public const int MaxLength = 254;

    /// <summary>
    /// Characters permitted unquoted in a local-part, beyond letters and digits
    /// (RFC 5322 "atext"). The dot is handled separately as an atom separator.
    /// </summary>
    private const string AdditionalAtomCharacters = "!#$%&'*+-/=?^_`{|}~";

    private EmailAddress(string localPart, DomainName domain, bool isQuoted)
    {
        LocalPart = localPart;
        Domain = domain;
        IsQuoted = isQuoted;
    }

    /// <summary>The local-part exactly as supplied, without surrounding quotes.</summary>
    public string LocalPart { get; }

    /// <summary>The domain part.</summary>
    public DomainName Domain { get; }

    /// <summary>True when the local-part required quoting.</summary>
    public bool IsQuoted { get; }

    /// <summary>
    /// The address as it should be written on the wire, with the domain in ASCII A-label
    /// form and the local-part re-quoted if it needs to be.
    /// </summary>
    public string Value => $"{FormatLocalPart()}@{Domain.Value}";

    /// <summary>
    /// The canonical comparison and storage key: lower-cased local-part, ASCII domain.
    /// Database unique indexes are built on this column.
    /// </summary>
    public string NormalizedValue => $"{LocalPart.ToLowerInvariant()}@{Domain.Value}";

    /// <summary>The address in Unicode form, for display and for SMTPUTF8 transport.</summary>
    public string UnicodeValue => $"{FormatLocalPart()}@{Domain.UnicodeValue}";

    /// <summary>
    /// True when this address can only be transmitted over a link advertising SMTPUTF8,
    /// because the local-part contains non-ASCII octets.
    /// </summary>
    public bool RequiresSmtpUtf8 => !Ascii.IsValid(LocalPart);

    /// <summary>Parses an address, throwing when it is not valid.</summary>
    /// <exception cref="InvalidValueObjectException">The input is not a valid address.</exception>
    public static EmailAddress Parse(string? input)
    {
        if (!TryParse(input, out EmailAddress? result, out string? error))
        {
            throw new InvalidValueObjectException(nameof(EmailAddress), error);
        }

        return result;
    }

    /// <summary>Attempts to parse an address. Use this on the SMTP path.</summary>
    public static bool TryParse(string? input, [NotNullWhen(true)] out EmailAddress? result) =>
        TryParse(input, out result, out _);

    /// <summary>Attempts to parse an address, reporting why it failed.</summary>
    public static bool TryParse(
        string? input,
        [NotNullWhen(true)] out EmailAddress? result,
        [NotNullWhen(false)] out string? error)
    {
        result = null;
        error = null;

        if (string.IsNullOrWhiteSpace(input))
        {
            error = "the value is empty.";
            return false;
        }

        string candidate = input.Trim();

        // Tolerate the angle-bracket form that arrives in SMTP commands and headers.
        if (candidate.StartsWith('<') && candidate.EndsWith('>'))
        {
            candidate = candidate[1..^1].Trim();
        }

        if (Encoding.UTF8.GetByteCount(candidate) > MaxLength)
        {
            error = $"the address exceeds the {MaxLength}-octet maximum.";
            return false;
        }

        // Split on the LAST '@'. A quoted local-part may legally contain one, and splitting
        // on the first would mis-parse "a@b"@example.com.
        int separator = candidate.LastIndexOf('@');
        if (separator <= 0 || separator == candidate.Length - 1)
        {
            error = "the address must be in the form local-part@domain.";
            return false;
        }

        string rawLocalPart = candidate[..separator];
        string rawDomain = candidate[(separator + 1)..];

        if (!TryParseLocalPart(rawLocalPart, out string? localPart, out bool isQuoted, out error))
        {
            return false;
        }

        if (!DomainName.TryParse(rawDomain, out DomainName? domain, out string? domainError))
        {
            error = $"the domain is invalid: {domainError}";
            return false;
        }

        result = new EmailAddress(localPart, domain, isQuoted);
        return true;
    }

    private static bool TryParseLocalPart(
        string raw,
        [NotNullWhen(true)] out string? localPart,
        out bool isQuoted,
        [NotNullWhen(false)] out string? error)
    {
        localPart = null;
        isQuoted = false;
        error = null;

        if (raw.Length == 0)
        {
            error = "the local-part is empty.";
            return false;
        }

        if (Encoding.UTF8.GetByteCount(raw) > MaxLocalPartLength)
        {
            error = $"the local-part exceeds the {MaxLocalPartLength}-octet maximum.";
            return false;
        }

        if (raw[0] == '"')
        {
            if (raw.Length < 2 || raw[^1] != '"')
            {
                error = "the quoted local-part is not terminated.";
                return false;
            }

            string inner = raw[1..^1];
            if (!IsValidQuotedString(inner, out error))
            {
                return false;
            }

            isQuoted = true;
            localPart = inner;
            return true;
        }

        if (raw[0] == '.' || raw[^1] == '.')
        {
            error = "the local-part may not start or end with a dot.";
            return false;
        }

        if (raw.Contains("..", StringComparison.Ordinal))
        {
            error = "the local-part may not contain consecutive dots.";
            return false;
        }

        foreach (char c in raw)
        {
            if (c == '.')
            {
                continue;
            }

            // Non-ASCII is permitted: this is an SMTPUTF8 address. RequiresSmtpUtf8 then
            // reports true, and the delivery path refuses to send it to a peer that has
            // not advertised SMTPUTF8 rather than corrupting it.
            if (!Ascii.IsValid(c))
            {
                if (char.IsControl(c))
                {
                    error = "the local-part contains a control character.";
                    return false;
                }

                continue;
            }

            if (char.IsAsciiLetterOrDigit(c) ||
                AdditionalAtomCharacters.Contains(c, StringComparison.Ordinal))
            {
                continue;
            }

            error = $"'{c}' must be quoted to appear in a local-part.";
            return false;
        }

        localPart = raw;
        return true;
    }

    private static bool IsValidQuotedString(string inner, [NotNullWhen(false)] out string? error)
    {
        error = null;

        for (int i = 0; i < inner.Length; i++)
        {
            char c = inner[i];

            if (c == '\\')
            {
                if (i + 1 >= inner.Length)
                {
                    error = "the quoted local-part ends with a dangling escape.";
                    return false;
                }

                i++;
                continue;
            }

            if (c == '"')
            {
                error = "an unescaped quote appears inside the quoted local-part.";
                return false;
            }

            if (char.IsControl(c))
            {
                error = "the quoted local-part contains a control character.";
                return false;
            }
        }

        return true;
    }

    private string FormatLocalPart()
    {
        if (!IsQuoted)
        {
            return LocalPart;
        }

        StringBuilder builder = new(LocalPart.Length + 4);
        builder.Append('"');
        foreach (char c in LocalPart)
        {
            if (c is '"' or '\\')
            {
                builder.Append('\\');
            }

            builder.Append(c);
        }

        builder.Append('"');
        return builder.ToString();
    }

    /// <summary>Equality is on <see cref="NormalizedValue"/> - see the type remarks.</summary>
    public bool Equals(EmailAddress? other) =>
        other is not null &&
        string.Equals(NormalizedValue, other.NormalizedValue, StringComparison.Ordinal);

    public override bool Equals(object? obj) => Equals(obj as EmailAddress);

    public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(NormalizedValue);

    public int CompareTo(EmailAddress? other) =>
        other is null ? 1 : string.CompareOrdinal(NormalizedValue, other.NormalizedValue);

    public override string ToString() => Value;

    public static bool operator ==(EmailAddress? left, EmailAddress? right) =>
        left?.Equals(right) ?? right is null;

    public static bool operator !=(EmailAddress? left, EmailAddress? right) => !(left == right);
}
